import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 * Created by android on 22/2/15.
 */
public class JMain {
    public static void main(String[] args) {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/demo1;create=true");
            
            String query1 = " create table \"Positions\" (\"positionName\" VARCHAR(254) NOT NULL,\"description\" VARCHAR(254) NOT NULL,\"positionId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)\n";
            System.out.println("create query: " + conn.createStatement().execute(query1));
            
            String query2 = " create table \"Players\" (\"playerName\" VARCHAR(254) NOT NULL,\"positionId\" INTEGER NOT NULL,\"playerId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)alter table \"Players\" add constraint \"player_positionId_fk\" foreign key(\"positionId\") references \"Positions\"(\"positionId\") on update NO ACTION on delete NO ACTION\n";
            System.out.println("create query: "+ conn.createStatement().execute(query2));
            
            String query3 = " create table \"Matches\" (\"tournamentName\" VARCHAR(254) NOT NULL,\"dateAndTime\" TIMESTAMP NOT NULL,\"venue\" VARCHAR(254) NOT NULL,\"opponentTeam\" VARCHAR(254) NOT NULL,\"matchId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)\n";
            System.out.println("create query: "+conn.createStatement().execute(query3));
            
            String query4 = " create table \"Teams\" (\"matchId\" INTEGER NOT NULL,\"playerId\" INTEGER NOT NULL,\"teamId\" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY)alter table \"Teams\" add constraint \"teams_matchId_fk\" foreign key(\"matchId\") references \"Matches\"(\"matchId\") on update NO ACTION on delete NO ACTIONalter table \"Teams\" add constraint \"teams_playerId_fk\" foreign key(\"playerId\") references \"Players\"(\"playerId\") on update NO ACTION on delete NO ACTION\n";
            System.out.println("create query: "+conn.createStatement().execute(query4));
            
            
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
